#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 09 14:48:56 CEST 2025
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_write_numbers_bram_behav -key {Behavioral:sim_1:Functional:tb_write_numbers_bram} -tclbatch tb_write_numbers_bram.tcl -view /home/lsriw/Documents/RN/RN_proj/Embedded/tb_write_numbers_bram_behav.wcfg -log simulate.log"
xsim tb_write_numbers_bram_behav -key {Behavioral:sim_1:Functional:tb_write_numbers_bram} -tclbatch tb_write_numbers_bram.tcl -view /home/lsriw/Documents/RN/RN_proj/Embedded/tb_write_numbers_bram_behav.wcfg -log simulate.log

